# Generated by Django 4.2 on 2024-07-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='number',
        ),
    ]
